### ISSUE TITLE
dumb readme.md

### ISSUE THREAD

**Issue by faith** [CS-Anti/CS-Anti#1]
So lets talk about readme.md. Both Linux Mint and Kali Linux shells are using Bash which is essentially a scripting language, also NPM is a essentially a package manager. Also you dont need to include such as WikipediaAPI, discord.py and discord.js id say since you aiready have Python and Javascript included abd WikipediaAPI is just a api so ye. Also same for social engineering like cmon like you would post anythin social engineering related on github.

**Comment by minegamer2000** [comment]
this

**Comment by HideakiAtsuyo** [comment]
this

**Comment by CS-Anti** [comment]
Aright ik but I just like explaining shit alot and divulging so people know what I do more specifically.

**Comment by faith** [comment]
> Aright ik but I just like explaining shit alot and divulging so people know what I do more specifically. 

Including every API you have used is unnecessary. I recommend you to only include Programming languages/frameworks.
